### ISSUE TITLE
How to integrate bluemix push notification service with parse server?

### ISSUE THREAD

**Issue by gowridev** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-nodejs#1]
Could you please guide me how to integrate bluemix push notification serice with [parse server](https://github.com/parse-server-modules/parse-server-push-adapter)

**Comment by srinivasannanduri** [comment]
The detailed blog here should help. 
https://www.ibm.com/blogs/bluemix/2016/02/migrating-from-parse-to-bluemix/
