### ISSUE TITLE
Error README.md

### ISSUE THREAD

**Issue by matiasdb** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-nodejs#3]
Hi S Venkatakrishnan.
I was reading how to implements the module with NodeJS. Your docs has a error on descriptions about parameters in setTarget function.
The first parameter are users (GCM key), not devices. 
I've also read scripts inside module and seeing the functions says.

this.setTarget = function(deviceIds, platforms, tagNames) {...}

In line number 49, Notification.js

Please tell me if it is incorrect or not.

Thanks.

**Comment by svkrish** [comment]
Hello Matias, are you looking at https://github.com/ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-nodejs/blob/master/lib/Notification.js which has 
this.setTarget = function(deviceIds, userIds, platforms, tagNames)

**Comment by matiasdb** [comment]
Yes. But in my script the function has only 3 parameters. 
Can you tell me why?

I installed the last version.

Thanks.

**Comment by svkrish** [comment]
We added the capability to support userID based notifications and to support that we have updated the scripts.   Where did you get your script from and when was this ?

**Comment by matiasdb** [comment]
Perfect. That's great. 
I executed the command "npm install bluemix-push-notifications --save" two days ago. I'll try to re-install the module today.
Sorry, but I have another question. When I put only one "deviceId" for to send a notification; all users received the notification. Do you know why? or what can I do?

Thanks again.

**Comment by svkrish** [comment]
You should not receive notification on any other device other than for which you have sent.  You are probably sending it 'by UserId' in which case multiple devices registered under the same UserId will all receive the notifications

**Comment by matiasdb** [comment]
Mmm, it's estrange because when I register my device on Bluemix, the response hasn't the userId, always is empty. However the token and deviceId is not empty.
Sorry, but I'm with this a week ago and I don't know how to resolve.

Thanks for help!
